:root {
  --bg-main: #0d1117;
  --bg-card: #161b22;
  --text-main: #e6edf3;
  --text-muted: #9da7b3;
  --accent: #4fd1ff;
  --accent-soft: rgba(79, 209, 255, 0.14);
}

title: "Ivan Caballos"
description: "Graduate Electronics Engineer | Circuit Design (Analog) | Embedded Systems | Laser/Photonics Electronics"

remote_theme: lewismiddleton/cayman-dark
plugins:
  - jekyll-remote-theme
